---
- name: Enable and start Apache service
  hosts: rhel
  become: true
  tasks:
    - name: Ensure Apache is running and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true 